### ISSUE TITLE
Pluto will not start. Throws 18 errors

### ISSUE THREAD

**Issue by brndnln** [brndnln/Pluto#2]
This is what it will throw.

```
error: Uncaught TypeError: TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
  Type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is missing the following properties from type 'Member': id, bot, tag, avatarURL, and 2 more.
  guild.members.set(payload.user.id, member);
                                     ~~~~~~
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/controllers/members.ts:25:38

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
  eventHandlers.guildMemberAdd?.(guild, member);
                                        ~~~~~~
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/controllers/members.ts:27:41

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
  guild.members.set(payload.user.id, member);
                                     ~~~~~~
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/controllers/members.ts:73:38

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
      member,
      ~~~~~~
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/controllers/members.ts:78:7

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
      eventHandlers.roleLost?.(guild, member, id);
                                      ~~~~~~
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/controllers/members.ts:87:39

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
      eventHandlers.roleGained?.(guild, member, id);
                                        ~~~~~~
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/controllers/members.ts:93:41

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
  eventHandlers.guildMemberUpdate?.(guild, member, cachedMember);
                                           ~~~~~~
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/controllers/members.ts:97:44

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
      await structures.createMember(
      ^
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/controllers/members.ts:110:7

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
      await structures.createMember(
      ^
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/controllers/messages.ts:29:7

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
        await structures.createMember(
        ^
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/controllers/messages.ts:41:9

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
            member,
            ~~~~~~
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/controllers/misc.ts:109:13

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
          eventHandlers.voiceChannelJoin?.(member, payload.channel_id);
                                           ~~~~~~
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/controllers/misc.ts:114:44

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
      eventHandlers.voiceChannelLeave?.(member, cachedState.channelID);
                                        ~~~~~~
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/controllers/misc.ts:118:41

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
  eventHandlers.voiceStateUpdate?.(member, payload);
                                   ~~~~~~
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/controllers/misc.ts:122:36

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
      await structures.createMember(
      ^
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/controllers/reactions.ts:44:7

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
      await structures.createMember(
      ^
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/controllers/reactions.ts:100:7

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
    guild.members.set(m.user.id, await structures.createMember(m, guild.id))
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/structures/guild.ts:95:34

TS2345 [ERROR]: Argument of type '{ user: { id: string; username: string; discriminator: string; avatar: string | null; bot?: boolean | undefined; system?: boolean | undefined; locale?: string | undefined; verified?: boolean | undefined; email?: string | undefined; flags?: number | undefined; }; ... 8 more ...; mute: boolean; }' is not assignable to parameter of type 'Member'.
  guild.members.set(id, member);
                        ~~~~~~
    at https://ex3wg4lq5lssdwbzdz4kewgzr2rnfn3xnccdgvze3gvjoedqlf2q.arweave.net/JfdjcXDq5SHYOR54oljZjqLSt3dohDNXJNmqlxBwWXU/src/handlers/guild.ts:198:25
```

**Comment by brndnln** [comment]
Replacing Discordeno with Discord.JS and Discord-Akairo

**Comment by brndnln** [comment]
Learn to use Akairo using typescript

**Comment by brndnln** [comment]
Fixed
